services:
  bot-db:
    container_name: somi-bot-db
    image: mariadb:12.0.2-noble
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mariadb
      - ./debug/logs:/var/log/mariadb
      - ./mariadb.cnf:/etc/mysql/mariadb.conf.d/mariadb.cnf
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - somi-network
    profiles:
      - dev
      - prod

  bot-backup:
    container_name: somi-bot-backup
    image: tiredofit/db-backup
    restart: unless-stopped
    volumes:
      - ./debug/backups:/backup
    environment:
      - TIMEZONE=Etc/UTC
      - CONTAINER_ENABLE_MONITORING=FALSE

      - DB01_TYPE=mariadb
      - DB01_HOST=${DB_HOST}
      - DB01_NAME=${DB_NAME}
      - DB01_USER=root
      - DB01_PASS=${DB_ROOT_PASSWORD}

      - DB01_BACKUP_BEGIN=0500
      - DB01_BACKUP_INTERVAL=1440 # 24 hours in minutes
      - DB01_CLEANUP_TIME=44640 # 31 days in minutes
      - DB01_COMPRESSION=GZ
    networks:
      - somi-network
    depends_on:
      - bot-db
    profiles:
      - prod

  bot-dev:
    build: .
    container_name: somi-bot-dev
    depends_on:
      bot-db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - somi-network
    profiles:
      - dev

  bot-prod:
    build: .
    container_name: somi-bot-prod
    restart: unless-stopped
    depends_on:
      bot-db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./debug/logs:/app/debug/logs
    networks:
      - somi-network
    profiles:
      - prod

networks:
  somi-network:
    driver: bridge

volumes:
  mariadb_data: